name: build/conda

# https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_call
on:
  workflow_call:
    inputs:
      micromamba-version:
        type: string
        description: 'The `micromamba` version to use.'
        required: false
        default: '1.4.9-0'
      python-version:
        type: string
        description: 'The Python version to use.'
        required: false
        default: '=3.11'
      devtools-version:
        type: string
        description: 'The `eq-devtools` version to use.'
        required: false
        default: '>=0.2.3'


jobs:

  build_package:
    name: Build Conda Package
    runs-on: ubuntu-latest
    steps:
      - id: show_debug_info
        name: Show Debug Info
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          # Show Debug Info
          echo "::group::User Info"
          id
          echo "::endgroup::"
          echo "::group::GitHub Context"
          echo "${GITHUB_CONTEXT}"
          echo "::endgroup::"
          echo "::group::Environment Variables"
          unset GITHUB_CONTEXT
          env | sort
          echo "::endgroup::"
          echo "::group::Git Info"
          which git
          git --version
          echo "::endgroup::"
      - id: setup_micromamba
        name: Create Python Environment
        # https://github.com/mamba-org/setup-micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: ${{ inputs.micromamba-version }}
          cache-environment: true
          condarc: |
            channels:
              - conda-forge
              - energy-quants
          environment-name: build
          create-args: >-
            python${{ inputs.python-version }}
            eq-devtools${{ inputs.devtools-version }}
      - id: checkout_source
        name: Checkout Source
        # https://github.com/actions/checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: build_package
        name: Build Package
        shell: bash -l {0}
        run: |
          set -euox pipefail
          devtool --version
          git describe --long
          devtool conda build
          echo "Use the below commands to install the package:" >> "${GITHUB_STEP_SUMMARY}"
          echo '```bash' >> "${GITHUB_STEP_SUMMARY}"
          echo "gh run download $GITHUB_RUN_ID -n conda-channel --dir .build/conda/dist" >> "${GITHUB_STEP_SUMMARY}"
          echo '```' >> "${GITHUB_STEP_SUMMARY}"
      - id: publish_artifact
        name: Publish Artifact
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: conda-channel
          path: .build/conda/dist
